# Note: I'm using this notebook for learning, I will produce a clean version once it is done.

- Pick up a story + data to work on it
- EDA -  clean your data and prepare it to build visuals that bring your story to life
- Predictive models - what do you what to predict? What is the best model? Make your decision
- Data modeling - prepare the data for your model
- Build your model, evaluate it and take those predictions as part of your story

Data downloaded from: https://engineering.teads.com/2020/08/24/machine-learning-dataset-1-predicting-engagement-in-video-ads/

Columns (from website)

- auction_id – unique id for identifying each line
- timestamp – the timestamp (in seconds) of the ad impression
- creative_duration – the total duration of the video that has been played
- campaign_id – the advertising campaign id
- advertiser_id – the advertiser id
- placement_id – the id of a zone in the web page where the video was played
- placement_language – the language of this zone
- website_id – the corresponding website id
- referer_deep_three – the URL of the page where the video was played, truncated at its 3rd level
- ua_country – the country of the user who saw the video
- ua_os – the user Operating System
- ua_browser – the user internet browser
- ua_browser_version – the user browser version
- ua_device – the user device
- user_average_seconds_played – the average duration the user watched video ads in the past. It can be null if the user never watched any ad.
- seconds_played – the observed time the video has been watched. This is the quantity we are trying to predict.

To do:

1) Save zipped datafile as data frame

2) EDA
* What are the most important variables? Look at those
* What is the difference between creative_duration and seconds_played?

3) Model: predicting seconds_played
* Train - test split
* Models to consider:
     * Regression
     * Maybe classification if there is a logical cut-off?

# Opening zipped datafile

In [10]:
datafile = 'data/dataset.csv.gz'

### solution from  works fine, but printhttps://stackoverflow.com/questions/12902540/read-from-a-gzip-file-in-pythoning makes the kernel crash and also, I need to save this to the dataframe.

import gzip
with gzip.open(datafile,'r') as fin:        
    for line in fin:        
        #print('got line', line)

In [11]:
# 1) Saving ipped data to dataframe

import pandas as pd
df = pd.read_csv(datafile)

In [12]:
df.head()

,auction_id,timestamp,creative_duration,creative_id,campaign_id,advertiser_id,placement_id,placement_language,website_id,referer_deep_three,ua_country,ua_os,ua_browser,ua_browser_version,ua_device,user_average_seconds_played,seconds_played
0,0008b046-b675-4f51-8ad6-fe06e5d81f8e,1517334694,25,198280,210671,7109.0,47216,fr,31838,de/golf/publish,ch,Windows,Microsoft Edge,16.0,PersonalComputer,NaN,9
1,00095bac-8fec-48c8-a17b-8f3878359e1d,1517270483,29,195285,210074,2270.0,77249,fr,46416,com/vinepair/articles,uk,Windows,Chrome,64.0,PersonalComputer,NaN,8
2,000c4c0c-0789-4e50-8ba6-a4be920ab482,1517339899,60,201430,214063,2643.0,25817,fr,20824,co.uk/hastingsobserver/news,uk,iOS,Facebook App,NaN,Tablet,NaN,1
3,000db509-3350-4cd9-b60a-d506fbd31f29,1517346542,29,198262,215400,2244.0,86526,fr,39091,com/slate/news-and-politics,us,Windows,Chrome,63.0,PersonalComputer,18.166666,1
4,001300de-8eda-480f-bec8-4b46ef6117f2,1517310926,29,174590,184750,3617.0,85350,fr,14796,co.uk/independent/arts-entertainment,uk,Windows,Firefox,58.0,PersonalComputer,NaN,0

# EDA

In [16]:
# Shape of final df

print(f"The data frame has {df.shape[0]} rows and {df.shape[1]} columns.")

The final data frame has 3000000 rows and 17 columns.

In [17]:
df.describe()

,timestamp,creative_duration,creative_id,campaign_id,advertiser_id,placement_id,website_id,ua_browser_version,user_average_seconds_played,seconds_played
count,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,2.958556e+06,3.000000e+06,3.000000e+06,2.399960e+06,1.099705e+06,3.000000e+06
mean,1.517319e+09,2.910934e+01,1.990696e+05,2.119606e+05,4.665226e+03,5.790617e+04,3.218541e+04,3.662273e+01,1.004955e+01,6.967639e+00
std,2.396673e+04,2.109566e+01,7.107768e+03,7.470406e+03,2.919001e+03,1.791304e+04,1.003381e+04,2.644128e+01,9.053615e+00,9.054720e+00
min,1.517270e+09,5.000000e+00,1.213690e+05,1.243910e+05,6.250000e+02,1.874900e+04,1.432100e+04,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.517300e+09,1.400000e+01,1.988620e+05,2.113480e+05,1.768000e+03,4.495100e+04,2.346300e+04,1.100000e+01,3.375000e+00,1.000000e+00
50%,1.517322e+09,2.800000e+01,2.012290e+05,2.137830e+05,3.774000e+03,6.194800e+04,3.247900e+04,4.100000e+01,8.500000e+00,4.000000e+00
75%,1.517339e+09,3.000000e+01,2.018620e+05,2.146310e+05,7.452000e+03,7.240800e+04,4.121400e+04,6.300000e+01,1.466667e+01,1.100000e+01
max,1.517357e+09,1.350000e+02,2.029200e+05,2.158850e+05,9.322000e+03,8.765900e+04,5.159200e+04,4.127000e+03,2.250000e+02,1.350000e+02